module:
  imports:
  - disable: false
    ignoreConfig: false
    path: github.com/bugoio/bugo-mod-thumbnail
  - disable: false
    ignoreConfig: false
    path: github.com/bugoio/bugo-sass-utilities
